### ISSUE TITLE
Update 1.10 - DB-Verbindung funktioniert nicht mehr

### ISSUE THREAD

**Issue by Manu-H** [Clive128/CMQuiz#6]
MIt Update von 1.10 funktioniert die Verbindung zur Datenbank nicht mehr D:

**Comment by Clive128** [comment]
Sollte erledigt sein ;)

**Comment by Clive128** [comment]
ok ich mache ihn nicht zu :octopus:

**Comment by Manu-H** [comment]
Doch doch, ich mach auf wens nicht geht
